apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-dok-notifikasjon-med-kontakt-info
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: teamdokumenthandtering
      application: doknotifikasjon-2
      access: readwrite
