apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-dok-journalpost-endret-test-of-file-existence
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"

spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
#  acl:
#    - team: teamdokumenthandtering
#      application: joarkhendelser
#      access: read
#    - team: teamdokumenthandtering
#      application: teamdokumenthandtering-goldengate
#      access: write