apiVersion: aiven.nais.io/v1
kind: AivenApplication
metadata:
  name: teamdokumenthandtering-goldengate
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  kafka:
    pool: {{pool}}
  secretName: {{secretName}}
  protected: true