apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-dok-journalfoering-q1
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: teamdigihot
      application: hm-joark-listener
      access: read
    - team: teamdokumenthandtering
      application: joarkhendelser-q1
      access: write
    - team: bidrag
      application: bidrag-dokument-arkiv-feature
      access: read
    - team: teamdagpenger
      application: dp-joark-mottak
      access: read
    - team: teamfamilie
      application: familie-ef-mottak
      access: read
    - team: teamfamilie
      application: familie-baks-mottak
      access: read
    - team: tpts
      application: tiltakspenger-mottak
      access: read
    - team: yrkesskade
      application: yrkesskade-melding-mottak
      access: read
    - team: dusseldorf
      application: sif-innsyn-api
      access: read
    - team: flex
      application: flex-joark-mottak
      access: read
    - team: arbeidsgiver
      application: dokumentfordeling
      access: read
    - team: teamforeldrepenger
      application: fpfordel
      access: read
    - team: teamforeldrepenger
      application: fpoversikt
      access: read
    - team: k9saksbehandling
      application: k9-fordel
      access: read
    - team: pensjon-saksbehandling
      application: pensr-q1
      access: read
    - team: pensjon-q1
      application: pensjon-pen-q1
      access: read
    - team: teamsykmelding
      application: syfosmpapirmottak
      access: read
    - team: helsearbeidsgiver
      application: syfoinntektsmelding
      access: read
    - team: aap
      application: soknad-api
      access: read
    - team: aap
      application: routing
      access: read
