apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-dok-notifikasjon-status
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: teamdokumenthandtering
      application: doknotifikasjon-2
      access: readwrite
    - team: teamdokumenthandtering
      application: dokdistdittnav
      access: read
    - team: teamdokumenthandtering
      application: varsel2
      access: read
    - team: teamsykmelding
      application: narmesteleder-varsel
      access: read
    - team: flex
      application: sykepengesoknad-narmesteleder-varsler
      access: read
    - team: pto
      application: veilarbaktivitet
      access: read
    - team: pto
      application: veilarbdialog
      access: read
    - team: min-side
      application: tms-kafka-manager
      access: read
    - team: min-side
      application: dittnav-event-aggregator
      access: read
    - team: min-side
      application: tms-doknotstatus-converter
      access: read
    - team: aap
      application: soknad-api
      access: read
