apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-dok-journalfoering
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: teamdokumenthandtering
      application: joarkhendelser
      access: write
    - team: bidrag
      application: bidrag-dokument-arkiv
      access: read
    - team: teamdigihot
      application: hm-joark-listener
      access: read
    - team: teamdagpenger
      application: dp-joark-mottak
      access: read
    - team: teamfamilie
      application: familie-ef-mottak
      access: read
    - team: tpts
      application: tpts-mottak
      access: read
    - team: tpts
      application: tpts-arena
      access: read
