apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-dok-journalfoering
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: teamdokumenthandtering
      application: joarkhendelser
      access: write
    - team: bidrag
      application: bidrag-dokument-arkiv
      access: read
    - team: teamdigihot
      application: hm-joark-listener
      access: read
    - team: teamdagpenger
      application: dp-joark-mottak
      access: read
    - team: teamfamilie
      application: familie-ef-mottak
      access: read
    - team: teamfamilie
      application: familie-ba-mottak
      access: read
    - team: teamfamilie
      application: familie-baks-mottak
      access: read
    - team: tpts
      application: tiltakspenger-mottak
      access: read
    - team: isa
      application: jfr-infotrygd-q2
      access: read
    - team: isa
      application: jfr-test-stream-dok-topic
      access: read
    - team: isa
      application: jfr-infotrygd
      access: read
    - team: isa
      application: jfr-arena
      access: read
    - team: isa
      application: jfr-arena-q2
      access: read
    - team: isa
      application: jfr-generell
      access: read
    - team: isa
      application: jfr-generell-q2
      access: read
    - team: dusseldorf
      application: sif-innsyn-api
      access: read
    - team: yrkesskade
      application: yrkesskade-melding-mottak
      access: read
    - team: flex
      application: flex-joark-mottak
      access: read
    - team: teamforeldrepenger
      application: fpfordel
      access: read
    - team: arbeidsgiver
      application: dokumentfordeling
      access: read
    - team: k9saksbehandling
      application: k9-fordel
      access: read
    - team: pensjon-saksbehandling
      application: pensr
      access: read
    - team: pensjon-saksbehandling
      application: pensr-q2
      access: read
    - team: teamsykmelding
      application: syfosmpapirmottak
      access: read
    - team: helsearbeidsgiver
      application: syfoinntektsmelding
      access: read