name: Deploy Kafka topic update to dev and prod

on:
  push:
    branches:
    - 'master'

jobs:
  detect-changed-topics:
    runs-on: ubuntu-latest
    outputs:
      changedTopics: ${{ steps.find-changed-topics.outputs.changedTopics }}
      topicsHaveChanged: ${{ steps.find-changed-topics.outputs.topicsHaveChanged }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: find-changed-topics
        run: |
          mapfile -t matrix < <(git diff-tree --diff-filter=d --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | awk -F/ '$1 == "kafka-aiven" && !a[$2]++ { print $2 }')
          if ! [[ $matrix ]]; then
            echo "No topics have been changed"
          else
            json=$(jq --null-input --compact-output '{topic: $ARGS.positional}' --args "${matrix[@]}")
            echo "The changed topics are:"
            printf '  %s\n' "${matrix[@]}"
            echo "topicsHaveChanged=true" >> "$GITHUB_OUTPUT"
            echo "changedTopics=$json" >> "$GITHUB_OUTPUT"
          fi

  deploy-to-dev-and-prod:
    needs: detect-changed-topics
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: needs.detect-changed-topics.outputs.topicsHaveChanged == 'true'
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.detect-changed-topics.outputs.changedTopics) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/${{ matrix.topic }}/topic.yaml
          VARS: kafka-aiven/${{ matrix.topic }}/dev-vars.yaml
          PRINT_PAYLOAD: true
      - name: Ensure prod-vars.yaml exists
        id: prod_vars_exist
        run: |
          [[ -e kafka-aiven/$TOPIC/prod-vars.yaml ]]
        env:
          TOPIC: ${{ matrix.topic }}
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: kafka-aiven/${{ matrix.topic }}/topic.yaml
          VARS: kafka-aiven/${{ matrix.topic }}/prod-vars.yaml
          PRINT_PAYLOAD: true
