name: Deploy Kafka topic update to dev and prod

on:
  push:
    branches:
    - 'master'

jobs:
  detect-changed-topics:
    runs-on: ubuntu-latest
    outputs:
      changedTopics: ${{ steps.find-changed-topics.outputs.changedTopics }}
      topicsHaveChanged: ${{ steps.find-changed-topics.outputs.topicsHaveChanged }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: find-changed-topics
        run: |
          MATRIX=$(git diff-tree --diff-filter=d --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | grep kafka-aiven/ | cut -d '/' -f 2 | sort -u | paste -d',' -s )
          echo The changed topics that will be updated are $MATRIX
          if [[  -z "${MATRIX// }" ]]; then
            echo "No topics have been changed"
            echo "topicsHaveChanged=false" >> $GITHUB_OUTPUT
            echo "changedTopics=[]" >> $GITHUB_OUTPUT
          else
            JSON=$(jq -c -n --arg v $MATRIX '{"topic": $v|split(",")}')
            echo "Setting output changedTopics to $JSON"
            echo "topicsHaveChanged=true" >> $GITHUB_OUTPUT
            echo "changedTopics=$JSON" >> $GITHUB_OUTPUT
          fi

  deploy-to-dev-and-prod:
    needs: detect-changed-topics
    runs-on: ubuntu-latest
    if: needs.detect-changed-topics.outputs.topicsHaveChanged == 'true'
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.detect-changed-topics.outputs.changedTopics) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/${{ matrix.topic }}/topic.yaml
          VARS: kafka-aiven/${{ matrix.topic }}/dev-vars.yaml
          PRINT_PAYLOAD: true
      - name: Check if prod-vars.yaml exist
        id: prod_vars_exist
        uses: andstor/file-existence-action@v1
        with:
          files: "kafka-aiven/${{ matrix.topic }}/prod-vars.yaml"
      - name: Deploy to prod
        if: steps.prod_vars_exist.outputs.files_exists == 'true'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: kafka-aiven/${{ matrix.topic }}/topic.yaml
          VARS: kafka-aiven/${{ matrix.topic }}/prod-vars.yaml
          PRINT_PAYLOAD: true